// src/components/Shared/NavHeader/index.tsx
import React from 'react';
// import '../../../styles/index.scss';
import '../../../styles/main.scss';
import '../../../styles/fonts.scss';

function NavHeader() {
  return (
    <header className="p-2 mb-4 border-bottom nav-main-bg">
      <div className="container d-flex flex-wrap">
        <ul className="nav justify-content-lg-start col-12 col-lg-auto me-lg-auto">
          <li className="nav-item">
            <a href="/" className="nav-link px-2 candy-shop nekogoo-header">
              NekoGoo
            </a>
          </li>
        </ul>
        <ul className="nav justify-content-center col-12 col-lg-auto me-lg-auto mb-2 mb-md-0">
          <li className="nav-item">
            <a href="/" className="nav-link ml-5 px-2 link-secondary">
              Home
            </a>
          </li>
          {/* <li className="nav-item"><a className="nav-link px-2 link-dark">Blog</a></li> */}
          <li className="nav-item">
            <a href="./about.html" className="nav-link ml-5 px-2 link-dark">
              About
            </a>
          </li>
        </ul>
      </div>
    </header>
  );
}

export { NavHeader };

// src/views/Shared/NavHeader.vue
<template>
  <header class="p-2 mb-4 border-bottom nav-main-bg">
    <nav class="container d-flex flex-wrap">
      <ul class="nav justify-content-lg-start col-12 col-lg-auto me-lg-auto">
        <li class="nav-item">
          <router-link router-link to="/" class="nav-link px-2 candy-shop nekogoo-header">NekoGoo</router-link>
        </li>
      </ul>
      <ul class="nav justify-content-center col-12 col-lg-auto me-lg-auto mb-2 mb-md-0">
        <li class="nav-item">
          <router-link router-link to="/" class="nav-link ml-5 px-2 link-secondary">Home</router-link>
        </li>
        <!-- <li class="nav-item"><a class="nav-link px-2 link-dark">Blog</a></li> -->
        <li class="nav-item">
          <router-link router-link to="/about" class="nav-link ml-5 px-2 link-dark">About</router-link>
        </li>
      </ul>
    </nav>
  </header>
</template>
