// src/pages/Home.tsx
import React from 'react';

function Home() {
  return (
    <main id="zoneLanding" className="container">
      <h1>Welcome to NekoGoo Baka Net!</h1>
      {/* <!-- <h2>Entertainment</h2> --> */}
      <hr />
      {/* <!-- <h3>Blog Articles</h3> --> */}
      <h3>News</h3>
      Get the latest info on stuff I have planned, am learning, or find interesting and worth a share.&nbsp; Content generally swings between wholesome, horny,
      and derpy.
      <br />
      <br />
      <div className="row">
        {/* <!-- <div className="col-4">
                <h5>Characters</h5>
                <ul>
                    <li><i>Character Assets</i>: body parts, mental traits, stat perks, etc.</li>
                    <li><i>Relationships</i>: character social status in relation to others</li>
                    <li><i>Reputations</i>: factions, tribes, towns, religions, clubs, etc.</li>
                    <li>Example 04</li>
                    <li>Example 05</li>
                    <li>Example 06</li>
                </ul>
            </div> --> */}
        <div className="col-lg-6">
          <h5>YouTube Channels</h5>
          <ul>
            <li>
              <a href="https://www.youtube.com/channel/UCx_4XIMPtT3HQb0emNfbAyg" target="_blank" rel="noreferrer">
                NekoGoo Clone
              </a>
              : MMDs, highlight clips, misc.
            </li>
            <li>
              <a href="https://www.youtube.com/channel/UCwV-V3E4slWUqHIRwqah0mQ" target="_blank" rel="noreferrer">
                NekoGoo Gaming
              </a>
              : edited game play
            </li>
            <li>
              <a href="https://www.youtube.com/channel/UCJWIf5l-3Ob5Al-DxksSA2w" target="_blank" rel="noreferrer">
                NekoGoo Reacts
              </a>
              : sharing opinions about other content
            </li>
            {/* <!-- <li><a href="https://www.youtube.com/channel/UCiY9FYfWK_xjyws6PupiG6g" target="_blank">NekoGoo Stream</a>: archive for past VoDs</li> --> */}
          </ul>
          {/* <!-- <h6>Planned</h6>
                <ul>
                    <li>NekoGoo Codes: programming, web design, unity, and more.</li>
                </ul> --> */}
        </div>
      </div>
      <br />
      <div className="row">
        <div className="col-sm-6">
          <h3>Streaming</h3>
          Catch me live on{' '}
          <a href="https://www.twitch.tv/NekoGooClone" target="_blank" rel="noreferrer">
            twitch.tv/NekoGooClone
          </a>{' '}
          for games and memes.&nbsp; I enjoy anything involving monster girls, superpowers, fantasy, and sci-fi.&nbsp; I can often be found casually streaming
          Final Fantasy XIV &amp; other random games.
        </div>
        <div className="col-sm-6">
          <h3>Games</h3>I am developing a lewd, text-based RPG that will be free-to-play in browser.&nbsp; It will feature a strong emphasis on body
          transformation, relationships, &amp; dynamic story content.
          {/* <!-- <br /> --> */}
          {/* <!-- Any support is appreciated but never required. --> */}
        </div>
      </div>
      <br />
    </main>
  );
}

export default Home;

// src/views/Home.vue
<script setup lang="ts"></script>

<template>
  <main id="zoneLanding" class="container">
    <h1>Welcome to NekoGoo Baka Net!</h1>
    <!-- <h2>Entertainment</h2> -->
    <hr />
    <!-- <h3>Blog Articles</h3> -->
    <h3>News</h3>
    Get the latest info on stuff I have planned, am learning, or find interesting and worth a share.&nbsp; Content generally swings between wholesome, horny,
    and derpy.
    <br />
    <br />
    <div class="row">
      <!-- <div class="col-4">
                <h5>Characters</h5>
                <ul>
                    <li><i>Character Assets</i>: body parts, mental traits, stat perks, etc.</li>
                    <li><i>Relationships</i>: character social status in relation to others</li>
                    <li><i>Reputations</i>: factions, tribes, towns, religions, clubs, etc.</li>
                    <li>Example 04</li>
                    <li>Example 05</li>
                    <li>Example 06</li>
                </ul>
            </div> -->
      <div class="col-lg-6">
        <h5>YouTube Channels</h5>
        <ul>
          <li>
            <a href="https://www.youtube.com/channel/UCx_4XIMPtT3HQb0emNfbAyg" target="_blank" rel="noreferrer">NekoGoo Clone</a>: MMDs, highlight clips, misc.
          </li>
          <li><a href="https://www.youtube.com/channel/UCwV-V3E4slWUqHIRwqah0mQ" target="_blank" rel="noreferrer">NekoGoo Gaming</a>: edited game play</li>
          <li>
            <a href="https://www.youtube.com/channel/UCJWIf5l-3Ob5Al-DxksSA2w" target="_blank" rel="noreferrer">NekoGoo Reacts</a>: sharing opinions about other
            content
          </li>
          <!-- <li><a href="https://www.youtube.com/channel/UCiY9FYfWK_xjyws6PupiG6g" target="_blank">NekoGoo Stream</a>: archive for past VoDs</li> -->
        </ul>
        <!-- <h6>Planned</h6>
        <ul>
            <li>NekoGoo Codes: programming, web design, unity, and more.</li>
        </ul> -->
      </div>
    </div>
    <br />
    <div class="row">
      <div class="col-sm-6">
        <h3>Streaming</h3>
        Catch me live on
        <a href="https://www.twitch.tv/NekoGooClone" target="_blank" rel="noreferrer">twitch.tv/NekoGooClone</a> for games and memes.&nbsp; I enjoy anything
        involving monster girls, superpowers, fantasy, and sci-fi.&nbsp; I can often be found casually streaming Final Fantasy XIV &amp; other random games.
      </div>
      <div class="col-sm-6">
        <h3>Games</h3>
        I am developing a lewd, text-based RPG that will be free-to-play in browser.&nbsp; It will feature a strong emphasis on body transformation,
        relationships, &amp; dynamic story content.
        <!-- <br /> -->
        <!-- Any support is appreciated but never required. -->
      </div>
    </div>
    <br />
  </main>
</template>

<style scoped></style>
