// client/src/app/shared/pages/home/home.component.ts
import { Component, OnInit } from '@angular/core';

@Component({
  selector: 'app-home',
  templateUrl: './home.component.html',
  styleUrls: ['./home.component.css'],
  standalone: true,
})
export class HomeComponent implements OnInit {
  // constructor() {}

  ngOnInit(): void {}
}

<div app-theme='main' fxLayout="row wrap" fxLayout.xs="column" fxLayoutAlign="center">
    <div fxFlex.gt-xs="95%" fxFlex.gt-md="80%" fxFlex>
        <main>
            <div fxLayout.gt-xs="row wrap" fxLayout="column" fxLayoutGap="24px grid" fxLayoutAlign="start start">
                <div fxFlex.gt-xs="50%" fxFlex>
                    <h1>Welcome to the NekoGoo Baka Hub!</h1>
                    <!-- <h2>Entertainment</h2> -->

                    <div style="text-align: center">
                        <figure>
                            <img src="assets/images/NekoGoo-01-A.png" class="rounded-img-bottom" alt="NekoGoo profile pic" />
                            <figcaption>
                                * art courtesy of
                                <a href="https://twitter.com/blyzzarde" target="_blank" rel="noreferrer">Blyzzarde</a>
                            </figcaption>
                        </figure>
                    </div>
                    <br />
                </div>

                <div fxFlex.gt-xs="50%" fxFlex>
                    <!-- <mat-divider></mat-divider> -->

                    <!-- <h3>Blog Articles</h3> -->
                    <h3>News</h3>

                    <p class="pad-text">
                        Get the latest info on stuff I have planned, am learning, or find interesting and worth a share.&nbsp; Content generally swings
                        between wholesome, horny, and derpy.
                    </p>
                    <h5>Current Plans</h5>
                    <p class="pad-text">
                        Lately, I have placed the majority of my time into game development.&nbsp; These early alpha stages will primarily focus on game
                        flow iterations and establishing a solid foundation of game mechanisms.&nbsp; Once the engine's in a stable enough state, an early
                        preview version of the game will be made publically available.
                        <!-- Beta stage will ensure the game engine is capable of running all content scenarios from local storage.&nbsp; The first major release patch -->
                        <!-- will connect the game to an API server and database that will support user-submitted content. -->
                    </p>
                    <p class="pad-text">
                        I will also occasionally be streaming, but it'll be rather sporatic with no schedule for the time being.&nbsp; I intend to make it
                        more routine once the game's baseline is complete.
                    </p>
                    <br />

                    <!-- <h5>YouTube Channels</h5>
                                <ul>
                                    <li>
                                        <a href="https://www.youtube.com/channel/UCx_4XIMPtT3HQb0emNfbAyg" target="_blank" rel="noreferrer">NekoGoo Clone</a>: MMDs, highlight
                                        clips, misc.
                                    </li>
                                    <li><a href="https://www.youtube.com/channel/UCwV-V3E4slWUqHIRwqah0mQ" target="_blank" rel="noreferrer">NekoGoo Gaming</a>: edited game
                                        play
                                    </li>
                                    <li>
                                        <a href="https://www.youtube.com/channel/UCJWIf5l-3Ob5Al-DxksSA2w" target="_blank" rel="noreferrer">NekoGoo Reacts</a>: sharing
                                        opinions about other content
                                    </li>
                                    <li><a href="https://www.youtube.com/channel/UCiY9FYfWK_xjyws6PupiG6g" target="_blank">NekoGoo Stream</a>: archive for past VoDs</li>
                                </ul>
                                <br /> -->

                    <!-- <h5>Characters</h5>
                                <ul>
                                    <li><i>Character Assets</i>: body parts, mental traits, stat perks, etc.</li>
                                    <li><i>Relationships</i>: character social status in relation to others</li>
                                    <li><i>Reputations</i>: factions, tribes, towns, religions, clubs, etc.</li>
                                </ul> -->

                    <!-- <h6>Planned</h6>
                                <ul>
                                    <li>NekoGoo Codes: programming, web design, unity, and more.</li>
                                </ul> -->

                    <div fxLayout.gt-xs="row wrap" fxLayout="column" fxLayoutGap="24px grid" fxLayoutAlign="start start">
                        <div fxFlex.gt-xs="50%" fxFlex>
                            <h3>Games</h3>
                            <p class="pad-text">
                                I am developing a lewd, text-based RPG that will be free-to-play in browser.&nbsp; It will feature a strong emphasis on body
                                transformation, relationships, &amp; dynamic story content.&nbsp; For beta, I intend to add cloud saves &amp; open up the game's
                                API to support community content.
                                <!-- <br /> -->
                                <!-- Any support is appreciated but never required. -->
                            </p>
                        </div>
                        <div fxFlex.gt-xs="50%" fxFlex>
                            <!-- <h3>Streaming</h3>
                            <p>
                                Catch me live on <a href="https://www.twitch.tv/NekoGooClone" target="_blank" rel="noreferrer">twitch.tv/NekoGooClone</a> for
                                games and memes.&nbsp; I enjoy anything involving monster girls, superpowers, fantasy, and sci-fi.&nbsp; I can often be found
                                casually streaming Final Fantasy XIV &amp; other random games.
                            </p> -->
                            <h3>Other Interests</h3>
                            <p class="pad-text">
                                I enjoy anything involving monster girls, HMVs, superpowers, fantasy, and sci-fi.&nbsp; I have been playing loads of action
                                rogue-lites these days. Some of my favs have been HoloCure - Save the Fans!, Halls of Torment, Soulstone Survivors, Boneraiser
                                Minions, and Deep Rock Galactic: Survivor.
                            </p>
                        </div>
                    </div>
                    <br /><br />
                </div>
            </div>

        </main>
    </div>
</div>

// src/pages/Home.tsx
import React from 'react';

function Home() {
  return (
    <main id="zoneLanding" className="container">
      <h1>Welcome to NekoGoo Baka Net!</h1>
      {/* <!-- <h2>Entertainment</h2> --> */}
      <hr />
      {/* <!-- <h3>Blog Articles</h3> --> */}
      <h3>News</h3>
      Get the latest info on stuff I have planned, am learning, or find interesting and worth a share.&nbsp; Content generally swings between wholesome, horny,
      and derpy.
      <br />
      <br />
      <div className="row">
        {/* <!-- <div className="col-4">
                <h5>Characters</h5>
                <ul>
                    <li><i>Character Assets</i>: body parts, mental traits, stat perks, etc.</li>
                    <li><i>Relationships</i>: character social status in relation to others</li>
                    <li><i>Reputations</i>: factions, tribes, towns, religions, clubs, etc.</li>
                    <li>Example 04</li>
                    <li>Example 05</li>
                    <li>Example 06</li>
                </ul>
            </div> --> */}
        <div className="col-lg-6">
          <h5>YouTube Channels</h5>
          <ul>
            <li>
              <a href="https://www.youtube.com/channel/UCx_4XIMPtT3HQb0emNfbAyg" target="_blank" rel="noreferrer">
                NekoGoo Clone
              </a>
              : MMDs, highlight clips, misc.
            </li>
            <li>
              <a href="https://www.youtube.com/channel/UCwV-V3E4slWUqHIRwqah0mQ" target="_blank" rel="noreferrer">
                NekoGoo Gaming
              </a>
              : edited game play
            </li>
            <li>
              <a href="https://www.youtube.com/channel/UCJWIf5l-3Ob5Al-DxksSA2w" target="_blank" rel="noreferrer">
                NekoGoo Reacts
              </a>
              : sharing opinions about other content
            </li>
            {/* <!-- <li><a href="https://www.youtube.com/channel/UCiY9FYfWK_xjyws6PupiG6g" target="_blank">NekoGoo Stream</a>: archive for past VoDs</li> --> */}
          </ul>
          {/* <!-- <h6>Planned</h6>
                <ul>
                    <li>NekoGoo Codes: programming, web design, unity, and more.</li>
                </ul> --> */}
        </div>
      </div>
      <br />
      <div className="row">
        <div className="col-sm-6">
          <h3>Streaming</h3>
          Catch me live on{' '}
          <a href="https://www.twitch.tv/NekoGooClone" target="_blank" rel="noreferrer">
            twitch.tv/NekoGooClone
          </a>{' '}
          for games and memes.&nbsp; I enjoy anything involving monster girls, superpowers, fantasy, and sci-fi.&nbsp; I can often be found casually streaming
          Final Fantasy XIV &amp; other random games.
        </div>
        <div className="col-sm-6">
          <h3>Games</h3>I am developing a lewd, text-based RPG that will be free-to-play in browser.&nbsp; It will feature a strong emphasis on body
          transformation, relationships, &amp; dynamic story content.
          {/* <!-- <br /> --> */}
          {/* <!-- Any support is appreciated but never required. --> */}
        </div>
      </div>
      <br />
    </main>
  );
}

export default Home;
